---
# Initial rollout is needed to configure dependencies
- include_vars: repositories.yml

  # Install Dependencies
- include: spark.yml

- name: Creating deployment base dirs
  file: path=/opt/mindmaps
        state=directory

- name: Creating .ssh directory
  file: path=/home/denis/.ssh
        mode=0700
        owner=denis
        group=denis
        state=directory

- name: Installing deploy key
  copy: content={{ ml_key }}
        dest=/home/denis/.ssh/{{ ml_key_name }}
        mode=0600
        owner=denis
        group=denis

- name: Cloning ML repository
  git: repo={{ ml_repository_url }}
       dest={{ ml_clone_dest }}
       clone=yes
       version={{ ml_branch }}
  when: deploy_ml == true

